"""Agent state definition for the LangGraph multi-agent workflow.

This module defines the shared state schema (AgentState) that is passed between
all nodes in the LangGraph StateGraph. Every agent reads from and writes to this
common TypedDict, which acts as the single source of truth for the entire
multi-agent conversation pipeline.

The state is initialized when a user message enters the graph and is
progressively enriched as each agent (Lead, Search, Analysis, Report) performs
its work. LangGraph automatically merges partial updates returned by each node
back into the full state.
"""

from __future__ import annotations

from typing import Annotated

from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


class AgentState(TypedDict):
    """Shared state passed between all agent nodes in the graph.

    This TypedDict serves as the "blackboard" for inter-agent communication.
    Each agent node receives the full state and returns a partial dict containing
    only the keys it wants to update. LangGraph handles merging.

    Attributes:
        messages: Chat history with LangGraph's message accumulator.
        search_results: Raw search output from the Search Agent.
        analysis_results: Analysis output from the Analysis Agent.
        report_data: Report generation output from the Report Agent.
        current_task: The task type decided by the Lead Agent.
        pending_tasks: Queue of tasks still to execute (for composite requests).
        session_id: Active chat session identifier.
        steps: Counter to prevent infinite loops in the agent graph.
    """

    # The full conversation history (user messages, AI responses, tool outputs).
    # Annotated with `add_messages` so that LangGraph *appends* new messages
    # rather than replacing the entire list. This is the primary channel for
    # streaming content back to the user interface.
    messages: Annotated[list, add_messages]

    # Stores the raw textual output produced by the Search Agent after querying
    # the GitHub API. Downstream agents (Analysis, Report) can read this to
    # avoid repeating the same search. Empty string when no search has been done.
    search_results: str

    # Stores the combined analysis output (README content, metadata, deep
    # analysis) produced by the Analysis Agent. The Report Agent reads this
    # field to generate formatted reports. Empty string when no analysis has
    # been performed.
    analysis_results: str

    # Holds the final report artifact (file path, URL, or inline content)
    # generated by the Report Agent. Empty string when no report exists yet.
    report_data: str

    # The task type that the Lead Agent has classified for the *current*
    # iteration of the graph. Valid values are "search", "analyze", "report",
    # or "chat". This field drives the conditional routing edges in graph.py.
    current_task: str

    # A FIFO queue of task keywords that still need to be executed. When a user
    # request decomposes into multiple intents (e.g., "search and report"), the
    # Lead Agent puts the first task in `current_task` and the rest here. After
    # each specialized agent finishes, the graph loops back to the Lead Agent
    # which pops the next task from this queue.
    pending_tasks: list[str]

    # An opaque identifier for the current chat session. Passed through to the
    # Report Agent so that generated reports can be associated with and stored
    # under the correct session directory.
    session_id: str

    # Monotonically increasing counter that is bumped every time the Lead Agent
    # is invoked. Used as a safety mechanism to cap the maximum number of
    # iterations and prevent infinite loops in the graph (the hard limit is 6
    # steps, checked in both graph.py and lead_agent.py).
    steps: int
